spring.application.name=miniprojet

# Database Connection (using the 'db' service name from docker-compose)
spring.datasource.url=jdbc:mysql://db:3306/iraninfo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security - Default User (Requirement: BO avec user/pass par défaut)
spring.security.user.name=admin
spring.security.user.password=admin

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration